## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -267.0
accel_x_max: 268.0
accel_y_min: -252.0
accel_y_max: 282.0
accel_z_min: -297.0
accel_z_max: 267.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-386.666, 164.582, 756.765]
magn_ellipsoid_transform: [[0.833594, 0.0185304, -0.0276002], [0.0185304, 0.874601, 0.0214440], [-0.0276002, 0.0214440, 0.992686]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 8.72
gyro_average_offset_y: -14.08
gyro_average_offset_z: 7.44
